apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: production
  labels:
    app: ostad-devops
spec:
  type: NodePort
  selector:
    app: ostad-devops
  ports:
  - port: 5002
    targetPort: 5000
    nodePort: 30002
    protocol: TCP
    name: http